### ISSUE TITLE
Support for parameterized TestCase methods

### ISSUE THREAD

**Issue by moodmosaic** [GreanTech/Exude#9]
Would it make sense to support parameterized `TestCase<T>` methods where the values can be supplied by an external data source?

Such data sources could be:
- Hard coded values
- Arbitrary values generated by FsCheck
- Constrained non-deterministic values generated by AutoFixture
- A Composite of the above similar to [CompositeDataAttribute](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture.xUnit.net/CompositeDataAttribute.cs) for data theories

Each data source would plug into the `FirstClassTestsAttribute` in a similar fashion as with the xUnit.net data theories.

**Comment by ploeh** [comment]
But, you can already do that :)

[Here](https://github.com/GreanTech/Exude/blob/67c8122061cad95572041b412d9126db259f1586/Src/Exude.UnitTests/Scenario.cs#L33-L36)'s a Parameterized Test using an external data source:

``` C#
public void AParameterizedTest(DateTimeOffset x, DateTimeOffset y)
{
    Assert.True(x < y);
}
```

and [here](https://github.com/GreanTech/Exude/blob/67c8122061cad95572041b412d9126db259f1586/Src/Exude.UnitTests/Scenario.cs#L38-L64)'s the data source for that test:

``` C#
[FirstClassTests]
public static TestCase<Scenario>[] RunAParameterizedTest()
{
    var testCases = new[] 
    {
        new 
        {
            x = new DateTimeOffset(2002, 10, 12, 18, 15, 0, TimeSpan.FromHours(1)),
            y = new DateTimeOffset(2007,  4, 21, 18, 15, 0, TimeSpan.FromHours(1))
        },
        new
        {
            x = new DateTimeOffset(1970, 11, 25, 16, 10, 0, TimeSpan.FromHours(1)),
            y = new DateTimeOffset(1972,  6,  6,  8,  5, 0, TimeSpan.FromHours(1))
        },
        new
        {
            x = new DateTimeOffset(2014, 3, 2, 17, 18, 45, TimeSpan.FromHours(1)),
            y = new DateTimeOffset(2014, 3, 2, 17, 18, 45, TimeSpan.FromHours(0))
        }
    };
    return testCases
        .Select(tc =>
            new TestCase<Scenario>(
                s => s.AParameterizedTest(tc.x, tc.y)))
        .ToArray();
}
```

That particular example has hard-coded values, but it could just as well have called into FsCheck or AutoFixture. It's _real_ code, instead of some weakly-typed, constrained attribute, so it can do whatever you want.

**Comment by moodmosaic** [comment]
Actually, that's the example that triggered me to make the question :)

I was wondering if it makes sense to parameterize at the `TestCase<T>` level. In the above example it is the `RunAParameterizedTest` method.

**Comment by ploeh** [comment]
> I was wondering if it makes sense to parameterize at the TestCase<T> level.

I don't understand what you mean by that... What do you have in mind?

Sure, the `RunAParameterizedTest` method is a bit verbose, compared to certain `[Theory]`-driven test that we're used to, but it solves a different set of problems:
- It can parameterize on objects that have no constant expression (like `DateTimeOffset`)
- It's strongly typed, and thus refactoring-safe

I'd still use `[InlineData]` for most Parameterized Tests, because it's much more succinct, but I think something like `RunAParameterizedTest` is preferable to `[ClassData]` and `[PropertyData]`.

**Comment by moodmosaic** [comment]
What I have in mind is whether or not it would be convenient to plug-in external data source(s) for supplying anonymous values.

For example, what if we didn't care about the _offset_ part of the `DateTimeOffset` instance?

```
[FirstClassTests]
public static TestCase<Scenario>[] RunAParameterizedTest(TimeSpan anonymousOffset)
{
    var testCases = new[] 
    {
        new 
        {
            x = new DateTimeOffset(2002, 10, 12, 18, 15, 0, anonymousOffset),
            y = new DateTimeOffset(2007,  4, 21, 18, 15, 0, anonymousOffset)
        }
    }
}
```

I haven't actually used Exude (yet) in any codebase so perhaps this scenario is probably not realistic.

**Comment by ploeh** [comment]
Then you could use a `Fixture` instance from within the method:

``` C#
[FirstClassTests]
public static TestCase<Scenario>[] RunAParameterizedTest()
{
    var fixture = new Fixture();
    var anonymousOffset = fixture.Create<TimeSpan>();
    var testCases = new[] 
    {
        new 
        {
            x = new DateTimeOffset(2002, 10, 12, 18, 15, 0, anonymousOffset),
            y = new DateTimeOffset(2007,  4, 21, 18, 15, 0, anonymousOffset)
        }
    }
}
```

**Comment by moodmosaic** [comment]
Yes, indeed. That makes sense, at least for the set of problems Exude [solves](https://github.com/GreanTech/Exude/issues/9#issuecomment-37304123). Thank you!
